# Generated by Django 2.0.1 on 2020-02-05 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('index', models.IntegerField(null=True)),
                ('app_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=4000)),
                ('cataegories', models.CharField(max_length=10000, null=True)),
                ('domain', models.CharField(max_length=10000, null=True)),
                ('education', models.CharField(max_length=10000, null=True)),
                ('country', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
