# Generated by Django 2.0.1 on 2020-02-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_opp_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='opp',
            name='country',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
