# Generated by Django 2.0.1 on 2020-02-04 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_opp_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opp',
            name='cataegories',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opp',
            name='domain',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opp',
            name='education',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
