# Generated by Django 2.0.1 on 2020-02-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200205_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opp',
            name='link',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opp',
            name='link2',
            field=models.URLField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opp',
            name='title',
            field=models.CharField(max_length=4000),
        ),
    ]
