# Generated by Django 2.0.1 on 2020-02-04 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200205_0246'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opp',
            old_name='id',
            new_name='Id',
        ),
    ]
